/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary": "#006a65",
        "primary-fixed": "#ffdad8",
        "inverse-primary": "#ffb3b0",
        "secondary-fixed": "#7cf6ec",
        "tertiary-container": "#9d9b9b",
        "tertiary-fixed": "#e5e2e1",
        "outline-variant": "#e0bfbd",
        "surface-dim": "#dbdad4",
        "surface-container-highest": "#e3e3dc",
        "primary-fixed-dim": "#ffb3b0",
        "on-error-container": "#93000a",
        "outline": "#8c706f",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#8c1520",
        "on-tertiary-container": "#333333",
        "on-surface": "#1b1c18",
        "secondary-container": "#79f3ea",
        "on-background": "#1b1c18",
        "on-primary-fixed": "#410006",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#474746",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#5dd9d0",
        "surface-container-low": "#f5f4ed",
        "surface": "#fafaf3",
        "surface-tint": "#ae2f34",
        "surface-container": "#efeee7",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e9e8e2",
        "on-tertiary-fixed": "#1c1b1b",
        "on-secondary-container": "#006f69",
        "inverse-surface": "#30312c",
        "tertiary": "#5f5e5e",
        "primary": "#ae2f34",
        "on-primary-container": "#6d0010",
        "on-tertiary": "#ffffff",
        "primary-container": "#ff6b6b",
        "surface-bright": "#fafaf3",
        "inverse-on-surface": "#f2f1ea",
        "surface-variant": "#e3e3dc",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-surface-variant": "#584140",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#00201e",
        "on-secondary-fixed-variant": "#00504c",
        "background": "#fafaf3"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
